# Generated by Django 4.2.5 on 2023-11-02 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='time_create',
            field=models.TimeField(default=datetime.datetime(2023, 11, 2, 13, 55, 34, 969402), verbose_name='Время создания'),
        ),
    ]
