# Generated by Django 4.2.5 on 2023-11-07 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Studio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='application',
            name='design',
        ),
    ]
