# Generated by Django 4.2.5 on 2023-11-02 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studio', '0002_alter_application_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2023, 11, 2, 15, 52, 33, 90631), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Новая', 'Новая'), ('Принято в работу', 'Принято в работу'), ('Выполнено', 'Выполнено')], default='Новая', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='application',
            name='time_create',
            field=models.TimeField(default=datetime.datetime(2023, 11, 2, 15, 52, 33, 90631), verbose_name='Время создания'),
        ),
    ]
