# Generated by Django 4.2.5 on 2023-11-02 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studio', '0003_application_date_create_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_create',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='application',
            name='time_create',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Время создания'),
        ),
    ]
