# Generated by Django 4.2.5 on 2023-11-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studio', '0004_alter_application_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, choices=[('bigApartment', 'bigApartment'), ('mediumApartment', 'mediumApartment'), ('smallApartment', 'smallApartment')], default='a', max_length=15, verbose_name='Категория'),
        ),
    ]
